# Generated by Django 5.0 on 2024-01-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('bug_title', models.CharField(max_length=255)),
                ('bug_description', models.TextField()),
                ('bug_steps', models.TextField()),
                ('bug_type', models.CharField(max_length=255)),
                ('bug_priority', models.CharField(max_length=255)),
            ],
        ),
    ]
